REFERENCE_RANGES = {
    "Total Leukocyte Count": {"min": 4.0, "max": 11.0, "unit": "x10^3/uL"},
    "RBC Count": {"min": 4.2, "max": 5.9, "unit": "million/uL"},
    "Hemoglobin": {"min": 13.0, "max": 17.0, "unit": "g/dL"},
    "Hematocrit": {"min": 40.0, "max": 50.0, "unit": "%"},
    "MCV": {"min": 80.0, "max": 100.0, "unit": "fL"},
    "MCH": {"min": 27.0, "max": 33.0, "unit": "pg"},
    "MCHC": {"min": 32.0, "max": 36.0, "unit": "g/dL"},
    "RDW-CV": {"min": 11.5, "max": 14.5, "unit": "%"},
    "Platelet Count": {"min": 150, "max": 450, "unit": "x10^3/uL"},
    "Neutrophils": {"min": 40, "max": 70, "unit": "%"},
    "Lymphocytes": {"min": 20, "max": 45, "unit": "%"},
    "Monocytes": {"min": 2, "max": 10, "unit": "%"},
    "Eosinophils": {"min": 1, "max": 6, "unit": "%"},
    "Basophils": {"min": 0, "max": 2, "unit": "%"},
    "Absolute Neutrophil Count": {"min": 2.0, "max": 7.0, "unit": "x10^3/uL"},
    "Absolute Lymphocyte Count": {"min": 1.0, "max": 3.0, "unit": "x10^3/uL"},
    "Absolute Monocyte Count": {"min": 0.2, "max": 1.0, "unit": "x10^3/uL"},
    "Absolute Eosinophil Count": {"min": 0.02, "max": 0.5, "unit": "x10^3/uL"},
    "Absolute Basophil Count": {"min": 0.0, "max": 0.1, "unit": "x10^3/uL"},
}
